export const properties = [
  {
    id: 1,
    category: "Land",
    title: "Prime Land Plot",
    location: "Hillcroft Heights Estate, Ogudu Foreshore",
    price: "₦160,000 / sqm",
    area: "200 acres",
    image: "/land1.png",
    images: ["/land1.png"],
    highlights: ["Prime access", "Ready for investment"],
  },
  {
    id: 9,
    category: "Land",
    title: "Oasis Palm Estate",
    location: "Oasis Palm Estate",
    price: "₦2,500,000",
    area: "—",
    image: "/oasispalm.png",
    highlights: ["Prime location", "Future development"],
  },
  {
    id: 4,
    category: "Building",
    title: "New Building Duplex",
    location: "Memudu Suberu St, Sangotedo, Lekki, Lagos",
    price: "₦220,000,000",
    beds: 4,
    baths: 3,
    area: "1331 sqm",
    image: "/sangotedo1.png",
    images: ["/sangotedo1.png", "/sangotedo2.png", "/sangotedo3.png"],
    highlights: ["Luxury finishes", "Secure enclave"],
  },
  {
    id: 5,
    category: "Building",
    title: "5 bedroom semi detached house",
    location: "Greenland estate, Anthony Village",
    price: "₦350,000,000",
    beds: 5,
    baths: 0,
    area: "—",
    image: "/building2.png",
    highlights: ["Offplan sales available", "Pay 40% now", "Pay 30% on completion"],
    isComingSoon: false,
  },
  {
    id: 6,
    category: "Land",
    title: "Coming Soon",
    location: "More Land Listings Soon",
    price: "Coming soon",
    area: "—",
    image: "/land1.png",
    images: ["/land1.png"],
    isComingSoon: true,
  },
  {
    id: 7,
    category: "Building",
    title: "Coming Soon",
    location: "More New Buildings Soon",
    price: "Coming soon",
    beds: 0,
    baths: 0,
    area: "—",
    image: "/building1.png",
    isComingSoon: true,
  },
  {
    id: 8,
    category: "Building",
    title: "Coming Soon",
    location: "More New Buildings Soon",
    price: "Coming soon",
    beds: 0,
    baths: 0,
    area: "—",
    image: "/project.png",
    isComingSoon: true,
  },
];
